/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tjvdknSvxVu
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";

export default function DNSDetailsScreen() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-50 dark:bg-gray-900">
      <header className="py-6 px-4 bg-white dark:bg-gray-800 shadow">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
          Online DNS Lookup Tool
        </h1>
      </header>
      <main className="flex-1 py-6 px-4">
        <div className="max-w-lg mx-auto">
          <div className="flex justify-between items-end mb-6">
            <div className="flex-grow mr-2">
              <Label htmlFor="domain">Domain Name</Label>
              <Input id="domain" placeholder="Enter domain name" />
            </div>
            <Button className="flex-shrink-0">Lookup DNS Records</Button>
          </div>
          <div className="mt-12 space-y-6">
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">
              DNS Records
            </h2>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Record Type</TableHead>
                  <TableHead>Record Value</TableHead>
                  <TableHead>Details</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>A</TableCell>
                  <TableCell>192.0.2.1</TableCell>
                  <TableCell>IPv4 address for www.example.com</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>MX</TableCell>
                  <TableCell>mail.example.com</TableCell>
                  <TableCell>Mail exchange record for example.com</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>CNAME</TableCell>
                  <TableCell>www.example.com</TableCell>
                  <TableCell>Canonical name for example.com</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </div>
      </main>
      <footer className="py-6 px-4 bg-white dark:bg-gray-800 shadow mt-12">
        <p className="text-center text-sm text-gray-500 dark:text-gray-400">
          © 2024 DNS Lookup Tool. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
